# Build settings
language = "python"
build_command = "pipenv run build"

# Deploy settings
target = "production"
environment = {
  DATABASE_URL = "postgresql://localhost:5432/isotopedb",
  SECRET_KEY = "my_secret_key",
   PORT = 8000,
}
